backend:
  name: github
  repo: lukemiller93/country-barn-builders

media_folder: static/assets
public_folder: assets

collections:
  - name: location
    label: Locations
    label_singular: Location
    folder: content/locations
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Location Name, widget: string, required: true }
      - { name: cover, label: Featured Image, widget: image, required: true }
      - { name: body, label: Body, widget: markdown }
