backend:
  name: git-gateway
  repo: lukemiller93/country-barn-builders

media_folder: static/assets
public_folder: assets
site_url: https://practical-mestorf-9c8a21.netlify.com
display_url: https://practical-mestorf-9c8a21.netlify.com

collections:
  - name: location
    label: Locations
    label_singular: Location
    folder: content/locations
    create: true
    fields:
      - { name: "locationTemplate", widget: "hidden", default: "location" }
      - {
          name: "title",
          label: "Location Name",
          widget: "string",
          required: true,
        }
      - name: "cover"
        label: "Featured Image"
        widget: "object"
        required: true
        fields:
          - label: "Image"
            name: "feature_image"
            widget: "image"
          - label: "Alt Text"
            name: "alt_text"
            widget: "string"
      - label: "Address"
        name: "address"
        widget: "object"
        fields:
          - { label: "Street Address", name: "street", widget: "string" }
          - { label: "City", name: "city", widget: "string" }
          - {
              label: "State",
              name: "state",
              widget: "string",
              pattern: ["[A-Z]{2}", "Enter state abbrev., must be all caps"],
            }
          - { label: "Postal Code", name: "post_code", widget: "string" }
      - label: "Phone"
        name: "phone"
        widget: "string"
      - label: "Business Hours"
        name: "business_hours"
        widget: "list"
        fields:
          - label: "Add Hours"
            name: "add_hours"
            widget: "object"
            fields:
              - {
                  label: "Day",
                  name: "day",
                  widget: string,
                  default: "Mon. - Fri.",
                }
              - {
                  label: "Hours",
                  name: "hours",
                  widget: string,
                  default: "8am - 5pm",
                }
